[[redirects]]
from = "/dashboard"
to = "https://comma-fanfare-drew.ngrok-free.dev/dashboard"
status = 200
force = true

[[redirects]]
from = "/dashboard/*"
to = "https://comma-fanfare-drew.ngrok-free.dev/dashboard/:splat"
status = 200
force = true
