[[redirects]]
from = "/dashboard"
to = "https://portal.serendibai.lk/dashboard"
status = 302
force = true

[[redirects]]
from = "/dashboard/*"
to = "https://portal.serendibai.lk/dashboard/:splat"
status = 302
force = true
